# Generated by Django 3.1.1 on 2020-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('servingSize', models.CharField(max_length=10)),
                ('calories', models.IntegerField()),
                ('totalFat', models.CharField(max_length=10)),
                ('cholesterol', models.CharField(max_length=10)),
                ('sodium', models.CharField(max_length=10)),
                ('totalCarb', models.CharField(max_length=10)),
                ('protein', models.CharField(max_length=10)),
            ],
        ),
    ]
