# Generated by Django 3.1.1 on 2020-10-17 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrihacker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='log_time',
            field=models.TimeField(),
        )
    ]
