# Generated by Django 3.1.1 on 2020-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0002_recipe_recipefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Custom Recipe', max_length=50),
        ),
    ]
