# Generated by Django 3.1.1 on 2020-10-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0004_recipe_recipefood'),
        ('nutrihacker', '0002_auto_20201016_2254'),
    ]

    operations = [
    ]
