# Generated by Django 3.1.1 on 2020-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0005_merge_20201017_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='users',
        ),
        migrations.RemoveField(
            model_name='dietpreference',
            name='users',
        ),
        migrations.AddField(
            model_name='allergy',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='nutrihacker.Profile'),
        ),
        migrations.AddField(
            model_name='dietpreference',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='nutrihacker.Profile'),
        ),
    ]
