# Generated by Django 3.1.1 on 2020-10-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0006_auto_20201017_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandedIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fdcIds', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
