# Generated by Django 3.1.1 on 2020-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0007_auto_20201019_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredientOne', models.CharField(max_length=30)),
                ('ingredientTwo', models.CharField(max_length=30)),
                ('ingredientThree', models.CharField(max_length=30)),
                ('ingredientFour', models.CharField(max_length=30)),
                ('ingredientFive', models.CharField(max_length=30)),
                ('ingredientSix', models.CharField(max_length=30)),
                ('ingredientSeven', models.CharField(max_length=30)),
                ('ingredientEight', models.CharField(max_length=30)),
            ],
        ),
    ]
