# Generated by Django 3.1.1 on 2020-10-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0008_recipepreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipefood',
            old_name='amount',
            new_name='portions',
        ),
    ]
