# Generated by Django 3.1.1 on 2020-10-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0009_auto_20201021_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipefood',
            name='portions',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
