# Generated by Django 3.1.1 on 2020-10-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0011_auto_20201021_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='in_progress',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='recipefood',
            name='portions_unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(default=''),
        ),
    ]
