# Generated by Django 3.1.1 on 2020-10-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0012_auto_20201022_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servingsProduced',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
