# Generated by Django 3.1.1 on 2020-10-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0013_recipe_servingsproduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipefood',
            name='allergy',
            field=models.ManyToManyField(null=True, to='nutrihacker.Allergy'),
        ),
        migrations.AddField(
            model_name='recipefood',
            name='diet',
            field=models.ManyToManyField(null=True, to='nutrihacker.DietPreference'),
        ),
    ]
