# Generated by Django 3.1.1 on 2020-11-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0018_auto_20201102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.allergy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.dietpreference'),
        ),
    ]
