# Generated by Django 3.1.1 on 2020-11-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0019_auto_20201102_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePreset',
        ),
    ]
