# Generated by Django 3.1.1 on 2020-11-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0020_delete_recipepreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.meallog')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.recipe')),
            ],
        ),
    ]
