# Generated by Django 3.1.1 on 2020-11-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0021_mealrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='nutrihacker.Allergy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, to='nutrihacker.DietPreference'),
        ),
    ]
