# Generated by Django 3.1.1 on 2020-11-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0021_mealrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.food')),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.meallog')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrihacker.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='mealrecipe',
            name='meal_log',
        ),
        migrations.RemoveField(
            model_name='mealrecipe',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='MealFood',
        ),
        migrations.DeleteModel(
            name='MealRecipe',
        ),
    ]
