# Generated by Django 3.1.1 on 2020-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0022_auto_20201113_2022'),
        ('nutrihacker', '0022_auto_20201112_2152'),
    ]

    operations = [
    ]
