# Generated by Django 3.1.1 on 2020-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0023_merge_20201116_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caloriegoal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
