# Generated by Django 3.1.1 on 2020-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0025_auto_20201203_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='foods',
            field=models.ManyToManyField(through='nutrihacker.RecipeFood', to='nutrihacker.Food'),
        ),
    ]
