# Generated by Django 3.1.1 on 2020-12-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0030_auto_20201209_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
