# Generated by Django 3.1.1 on 2020-12-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0031_auto_20201209_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='profile_picture/'),
        ),
    ]
