# Generated by Django 3.1.1 on 2020-12-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0032_auto_20201209_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default.jpg', upload_to='profile_picture/'),
        ),
    ]
