# Generated by Django 3.1.1 on 2020-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrihacker', '0034_auto_20201209_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank='True', default='default.jpg', null='True', upload_to='profile_picture/'),
        ),
    ]
